# Generated by Django 4.2.13 on 2024-06-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mymodel",
            name="file",
            field=models.FileField(default=None, null=True, upload_to="uploads/"),
        ),
    ]
