# Generated by Django 4.2.13 on 2024-06-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_mymodel_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mymodel",
            name="file",
            field=models.FileField(default="uploads/default.csv", upload_to="uploads/"),
        ),
    ]
